version: "3.9"

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  backend:
    image: node:18-alpine
    working_dir: /workspace
    env_file:
      - ../.env
    command: sh -c "npm install && npm run start:backend"
    volumes:
      - ..:/workspace:cached
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis

  frontend:
    image: node:18-alpine
    working_dir: /workspace
    env_file:
      - ../.env
    command: sh -c "npm install && npm run start:frontend"
    volumes:
      - ..:/workspace:cached
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  pgdata:
  redisdata:
